openapi: 3.0.0
info:
  description: SafeZone API
  version: 1.0.0
  title: SafeZone API

servers:
  - url: /api

paths:
  /crimes/nearby:
    get:
      parameters:
        - name: latitude
          in: query
          required: true
          description: Latitude of a Coordinate
          schema:
            type: number
            format: float
        - name: longitude
          in: query
          required: true
          description: Longitude of a Coordinate
          schema:
            type: number
            format: float
        - name: filter
          in: query
          required: false
          description: Crime Categories to filter Crime Occurrences by
          schema:
            type: array
            items:
              type: number
              minimum: 1
              maximum: 12
            uniqueItems: true
            minItems: 1
            maxItems: 12
        - name: timeSpan
          in: query
          required: false
          description: Time Span to filter Crime Occurences by
          schema:
            type: string
            enum:
              - week
              - month
              - year

      operationId: server.routes.crimes.nearby_crimes
      tags:
        - Crimes
      summary: List crime occurrences within 500ft of a coordinate
      description: Provide list of Crime Occurrences
      responses: 
        200:
          description: A JSON array of crime occurrences
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Crime'
            
  /stations/nearby:
    get:
      parameters:
        - name: latitude
          in: query
          required: true
          description: Latitude of a Coordinate
          schema:
            type: number
            format: float
        - name: longitude
          in: query
          required: true
          description: Longitude of a Coordinate
          schema:
            type: number
            format: float
        - name: limit
          in: query
          required: false
          description: Number of Stations to return
          schema:
            type: number
      operationId: server.routes.stations.nearby_stations
      tags: 
        - Stations
      summary: List Subway Stations that are within 1/4 mile of a coordinate
      description: Provide list of station occurrences
      responses:
        200:
          description: A JSON array of Subway Stations
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/Station'


components:
  schemas:
    Crime:
      type: object
      properties:
        category:
          type: string
        date:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        crime_desc:
          type: string
    Station:
      type: object
      properties:
        name:
          type: string
        line:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
