openapi: 3.0.0
info:
  description: SafeZone API
  version: 1.0.0
  title: SafeZone API

servers:
  - url: /api

paths:
  /crimes/nearby:
    get:
      parameters:
        - name: latitude
          in: query
          required: true
          description: Latitude of a Coordinate
          schema:
            type: number
            format: float
        - name: longitude
          in: query
          required: true
          description: Longitude of a Coordinate
          schema:
            type: number
            format: float
        - name: filter
          in: query
          required: false
          description: |
            ## Crime Categories to filter by:
            1 -> Murder
            
            2 -> Rape
            
            3 -> Robbery
            
            4 -> Felony Assault
            
            5 -> Burglary
            
            6 -> Grand Larceny
            
            7 -> Petit Larceny
            
            8 -> Misdemeanor Assault
            
            9 -> Misdemeanor Sex Crimes
            
            10 -> Kidnapping
            
            11 -> Offenses against Public Order
            
            12 -> Shootings
          schema:
            type: array
            items:
              type: number
              minimum: 1
              maximum: 12
            uniqueItems: true
            minItems: 1
            maxItems: 12
        - name: timeSpan
          in: query
          required: false
          description: |
            ## Time Span to filter Crime Occurences by
          schema:
            type: string
            enum:
              - week
              - month
              - year

      operationId: server.routes.crimes.nearby_crimes_by_point
      tags:
        - Crimes
      summary: List crime occurrences within 500ft of a coordinate
      description: | 
        # Provide list of Crime Occurrences
      responses: 
        200:
          description: A JSON consisting of an array of crime occurrences and the frequencies of each category
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items: 
                      $ref: '#/components/schemas/Crime'
                  frequencies: 
                    $ref: '#/components/schemas/Frequencies'

        401:
          $ref: '#/components/responses/UnauthorizedError'
            
  /stations/nearby:
    get:
      parameters:
        - name: latitude
          in: query
          required: true
          description: Latitude of a Coordinate
          schema:
            type: number
            format: float
        - name: longitude
          in: query
          required: true
          description: Longitude of a Coordinate
          schema:
            type: number
            format: float
      operationId: server.routes.stations.nearby_stations
      tags: 
        - Stations
      summary: List Subway Stations that are within 1/4 mile of a coordinate
      description: | 
        ## Provide list of station occurrences
      responses:
        200:
          description: A JSON array of Subway Stations
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/Station'
        401:
          $ref: '#/components/responses/UnauthorizedError'

security:
  - API_KEY_AUTH: []

components:
  securitySchemes:
    API_KEY_AUTH:
      type: apiKey
      description: API KEY in order to access endpoints
      in: query
      name: API_KEY
      x-apikeyInfoFunc: 'server.auth.authenticated'
  responses:
    UnauthorizedError:
      description: API key is missing or invalid
  schemas:
    Crime:
      type: object
      properties:
        category:
          type: string
        date:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        ofns_desc:
          type: string
        pd_desc:
          type: string
    Station:
      type: object
      properties:
        id:
          type: number
          format: integer
        name:
          type: string
        lines:
          type: array
          items:
            type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
    Frequencies:
      type: object
      properties:
        Murder:
          type: number
        Rape:
          type: number
        Robbery:
          type: number
        Felony Assault:
          type: number
        Burglary:
          type: number
        Grand Larceny:
          type: number
        Petit Larceny:
          type: number
        Misdemeanor Assault:
          type: number
        Misdemeanor Sex Crimes:
          type: number
        Kidnapping:
          type: number
        Offenses against Public Order:
          type: number
        Shootings:
          type: number

