openapi: 3.0.0
info:
  description: SafeZone API
  version: 1.0.0
  title: SafeZone API

servers:
  - url: /api

paths:
  /crimes/nearby:
    get:
      parameters:
        - name: latitude
          in: query
          required: true
          description: Latitude of a Coordinate
          schema:
            type: number
            format: float
        - name: longitude
          in: query
          required: true
          description: Longitude of a Coordinate
          schema:
            type: number
            format: float
        - name: filter
          in: query
          required: false
          description: Crime Categories to filter by
          schema:
            $ref: '#/components/schemas/Filter'
        - name: timeSpan
          in: query
          required: false
          description: Time Span to filter Crime Occurences by
          schema:
            $ref: '#/components/schemas/Time Range'

      operationId: server.routes.crimes.nearby_crimes_by_point
      tags:
        - Crimes
      summary: List crime occurrences within 500ft of a coordinate
      description: | 
        # Provide list of Crime Occurrences
      responses: 
        200:
          description: A JSON consisting of an array of crime occurrences and the frequencies of each category
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items: 
                      $ref: '#/components/schemas/Crime'
                  frequencies: 
                    $ref: '#/components/schemas/Frequencies'

        401:
          $ref: '#/components/responses/UnauthorizedError'
            
  /stations/nearby:
    get:
      parameters:
        - name: latitude
          in: query
          required: true
          description: Latitude of a Coordinate
          schema:
            type: number
            format: float
        - name: longitude
          in: query
          required: true
          description: Longitude of a Coordinate
          schema:
            type: number
            format: float
      operationId: server.routes.stations.nearby_stations_all
      tags: 
        - Stations
      summary: List Subway Stations that are within 1/2 mile of a coordinate or the five nearest stations
      description: | 
        ## Provide list of nearby subway stations, its percentile, frequencies of crimes, and list of crime occurrences for each
      responses:
        200:
          description: A JSON array of Subway Stations
          content: 
            application/json:
              schema: 
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      format: integer
                    name:
                      type: string
                    lines:
                      type: array
                      items:
                        type: string
                    latitude:
                      type: number
                      format: float
                    longitude:
                      type: number
                      format: float
                    percentile:
                      type: number
                      format: float
        401:
          $ref: '#/components/responses/UnauthorizedError'

  /stations/rank:
    get:
      parameters:
        - name: station_ids
          in: query
          required: false
          description: Station IDs
          schema:
            type: array
            items:
              type: number
              minimum: 1
              maximum: 473
            uniqueItems: true
            minItems: 1
            maxItems: 473
        - name: filter
          in: query
          required: false
          description: Crime Categories to filter by
          schema:
            $ref: '#/components/schemas/Filter'
        - name: timeSpan
          in: query
          required: false
          description: Time Span to filter Crime Occurences by
          schema:
            $ref: '#/components/schemas/Time Range'
      operationId: server.routes.stations.station_risk_percent
      tags:
        - Stations
      summary: Gives percentile ranking for subway stations based on given station ids or all stations if no ids are given
      description: |
        ## List of stations
      responses:
        200:
          description: A JSON consisting of an subway stations with their percentile rank
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    format: integer
                  name:
                    type: string
                  lines:
                    type: array
                    items:
                      type: string
                  percentile:
                    type: number
                    format: float
        401: 
          $ref: '#/components/responses/UnauthorizedError'

  /route:
    get:
      parameters:
        - name: origin_latitude
          in: query
          required: true
          description: Latitude of origin coordinate
          schema:
            type: number
            format: float
        - name: origin_longitude
          in: query
          required: true
          description: Longitude of origin coordinate
          schema:
            type: number
            format: float
        - name: dest_latitude
          in: query
          required: true
          description: Latitude of destination coordinate
          schema:
            type: number
            format: float
        - name: dest_longitude
          in: query
          required: true
          description: Longitude of destination coordinate
          schema:
            type: number
            format: float
      operationId: server.routes.routes.route
      tags:
        - Routes
      summary: Gives safe directions from a given origin coordinate to a destination coordinate
      description: |
        ## Steps
      responses:
        200:
          description: A JSON consisting of steps
          content:
            application/json:
              schema:
                type: object
        401: 
          $ref: '#/components/responses/UnauthorizedError'

security:
  - API_KEY_AUTH: []

components:
  securitySchemes:
    API_KEY_AUTH:
      type: apiKey
      description: API KEY in order to access endpoints
      in: query
      name: API_KEY
      x-apikeyInfoFunc: 'server.auth.authenticated'
  responses:
    UnauthorizedError:
      description: API key is missing or invalid
  schemas:
    Filter:
      type: array
      items:
        type: number
        minimum: 1
        maximum: 12
      uniqueItems: true
      minItems: 1
      maxItems: 12
    Time Range:
      type: string
      enum:
        - "week"
        - "month"
        - "3 month"
        - "6 month"
        - "9 month"
        - "year"
    Crime:
      type: object
      properties:
        category:
          type: string
        date:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        ofns_desc:
          type: string
        pd_desc:
          type: string
    Frequencies:
      type: object
      properties:
        Murder:
          type: number
        Rape:
          type: number
        Robbery:
          type: number
        Felony Assault:
          type: number
        Burglary:
          type: number
        Grand Larceny:
          type: number
        Petit Larceny:
          type: number
        Misdemeanor Assault:
          type: number
        Misdemeanor Sex Crimes:
          type: number
        Kidnapping:
          type: number
        Offenses against Public Order:
          type: number
        Shootings:
          type: number

