openapi: "3.0.0"
info:
  description: SafeZone API
  version: "1.0.0"
  title: SafeZone API

servers:
  - url: 'http://127.0.0.1/api'

paths:
  /crimes/nearby:
    get:
      operationId: "server.routes.crimes.nearby_crimes"
      tags:
        - "Crimes"
      summary: "Crime occurrences within 500ft of the location"
      description: "Provide list of Crime Occurrences"
      responses: 
        200:
          description: "A JSON array of crime occurrences"
          content:
            application/json:
              schema:
                type: "array"
                items: 
                  properties:
                    category:
                      type: "string"
                    date:
                      type: "string"
                    latitude:
                      type: "number"
                    longitude:
                      type: "number"
                    pd_desc:
                      type: "string"
            